// Generated by CoffeeScript 1.3.3
(function() {
  var context, determine, hasDetermined, isBrowser, isNodeJS;

  hasDetermined = false;

  isNodeJS = false;

  isBrowser = false;

  context = this;

  determine = function(nodeJS) {
    if (nodeJS == null) {
      nodeJS = true;
    }
    hasDetermined = true;
    isNodeJS = nodeJS;
    isBrowser = !isNodeJS;
    return context = isBrowser ? window : this;
  };

  if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      determine();
    }
  }

  if (!hasDetermined) {
    determine(false);
  }

  module.exports = {
    hasDetermined: hasDetermined,
    isNodeJS: isNodeJS,
    isBrowser: isBrowser,
    context: context
  };

}).call(this);
